import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import fs from 'node:fs';
import { createScoreAdapter, emptyScoreState, buildScoreHistory } from '../modules/multipliers/score-adapter.js';
import { buildMultiplierOverviewSource, selectMultiplierOverview, multiplierPeriodHighlights, multiplierEfficiency } from '../modules/multipliers/overview-model.js';
import { historicalScoreBefore, multiplierHourlyScoreGrowth, multiplierValueProgress, multiplierEfficiencyGrowth } from '../modules/multipliers/tradeoff-model.js';
import { renderMultiplierOverview, multiplierOverviewCsv, overviewChart, renderMultiplierOverviewPanel } from '../modules/multipliers/overview-view.js';
const spec = JSON.parse(fs.readFileSync(new URL('../data/contest_scoring_spec.json', import.meta.url)));
function adapter(id) { return createScoreAdapter({ analyticalMetadata: { rule: spec.rule_sets.find((rule) => rule.id === id), contributions: [] } }); }
const state = { ...emptyScoreState(), points: 10000, raw: 100, weighted: 100 };
const product = adapter('wrtc_2026');
assert.equal(product.score({ ...state, points: 10002, raw: 101 }) - product.score(state), 10202);
assert.equal(product.score({ ...state, raw: 101 }) - product.score(state), 10000);
assert.equal(product.score({ ...state, points: 10002 }) - product.score(state), 200);
assert.equal(adapter('sarl_vhf_2026').score({ ...state, bandPoints: { '20M': 10, '40M': 20 }, bandMults: { '20M': 2, '40M': 3 } }), 80);
assert.equal(adapter('volta_rtty_2026').score({ ...state, positiveQsoCount: 2 }), 2000000);
assert.equal(adapter('ukr_champ_rtty_2026').score(state), 10500);
const rdaState = { ...state, groups: { rda_district: 4, country_for_ru_entries: 3 }, raw: 7 };
const foreignRda = createScoreAdapter({ analyticalMetadata: { rule: spec.rule_sets.find((r) => r.id === 'rda'), contributions: [], stationIsRu: false } });
assert.equal(foreignRda.score(rdaState), 40000, 'non-Russian RDA uses districts only');
assert.equal(adapter('rda').supported, false, 'missing RDA station perspective cannot be inferred');
const russianRda = createScoreAdapter({ analyticalMetadata: { rule: spec.rule_sets.find((r) => r.id === 'rda'), contributions: [], stationIsRu: true } });
assert.equal(russianRda.score(rdaState), 70000, 'Russian RDA also uses country credits');
assert.equal(adapter('rf_championship_cw').score(state), 10000, 'RF bonuses are already included in emitted QSO points');
const aegean = createScoreAdapter({ analyticalMetadata: { rule: spec.rule_sets.find((r) => r.id === 'aegean_rtty_legacy'), contributions: [], operatorQrpBonus: 20 } });
assert.equal(aegean.score(emptyScoreState()), 20, 'entrant QRP bonus is an explicit opening score');
assert.equal(aegean.score(state), 10020);
assert.equal(adapter('aegean_rtty_legacy').supported, false, 'missing fixed bonus must not be inferred from final totals');
const require = createRequire(import.meta.url);
require('../modules/analysis/core.js');
const core = globalThis.SH6AnalysisCore;
const fixture = fs.readFileSync(new URL('./fixtures/radio-m2.log', import.meta.url), 'utf8');
const parsed = core.parseLogFile(fixture, 'radio-m2.log');
const resources = { scoringSpec: spec, ctyTable: core.parseCtyDat(fs.readFileSync(new URL('../cty.dat', import.meta.url), 'utf8')), masterCalls: [] };
const derived = core.buildDerived(parsed.qsos, { logFile: { name: 'radio-m2.log' }, events: parsed.events, qtcs: parsed.qtcs, scoringRuleOverride: 'wrtc_2026' }, resources);
for (const [call, expected] of [['JA1AA', ['jidx_dxcc_for_ja', 'jidx_cq_zone_for_ja']], ['S50A', ['jidx_prefecture_for_dx']]]) {
  const log = core.parseLogFile(fixture.replace('CONTEST: IARU-HF', 'CONTEST: JIDX-CW').replaceAll('TEST1', call), 'jidx.log');
  const analysis = core.buildDerived(log.qsos, { logFile: { name: 'jidx.log' }, events: log.events, qtcs: log.qtcs }, resources);
  assert.equal(analysis.scoring.ruleId, 'jidx_cw');
  assert.deepEqual(analysis.scoring.analyticalMetadata.targetDescriptors.groups.map((group) => group.id), expected, 'scorer emits station-applicable JIDX targets');
}
for (const [contest, key, expected] of [['RSGB-NFD', 'modes', ['CW']], ['WIA-REMEMBRANCE', 'excludedBands', ['30M', '17M', '12M']]]) {
  const log = core.parseLogFile(fixture.replace('CONTEST: IARU-HF', `CONTEST: ${contest}`), 'target-rules.log');
  const analysis = core.buildDerived(log.qsos, { logFile: { name: 'target-rules.log' }, events: log.events, qtcs: log.qtcs }, resources);
  assert.deepEqual(analysis.scoring.analyticalMetadata.targetDescriptors[key], expected, 'target descriptors preserve explicit scorer restrictions');
}
const source = buildMultiplierOverviewSource(parsed.qsos, derived.scoring, derived.contestMeta, parsed.events);
source.classifyHistoricalStyles = core.classifyHistoricalOperatingStyles;
const styleCutoff = parsed.qsos[0].ts;
const priorStyles = core.classifyHistoricalOperatingStyles(parsed.qsos, styleCutoff);
const originalStyles = parsed.qsos.map((q) => q.operatingStyleRole);
const futureQso = { ...parsed.qsos[0], ts: styleCutoff + 60000, operatingStyleRole: 'RUN' };
assert.deepEqual(core.classifyHistoricalOperatingStyles([...parsed.qsos, futureQso], styleCutoff), priorStyles, 'future QSOs cannot change historical style labels');
assert.deepEqual(parsed.qsos.map((q) => q.operatingStyleRole), originalStyles, 'historical classification never mutates full-log labels');
const history = buildScoreHistory(source);
assert.equal(history.supported, true, history.reason);
assert.equal(history.rows.at(-1).score, derived.scoring.computedScore);
assert.equal(history.rows.length, 2, 'equal timestamps form one historical state');
assert.equal(history.eventGrowth.reduce((sum, value) => sum + value, 0), derived.scoring.computedScore);
const selection = selectMultiplierOverview(source);
const hourlyScores = multiplierHourlyScoreGrowth(selection);
const valueTarget = { band: '20M', group: 'country', scopeKey: '20M', countingScope: 'per_band', averagePoints: 2, weight: 1 };
const values = multiplierValueProgress(source, valueTarget, selection.start, selection.end);
assert.equal(values[0].multiplier, 0, 'opening value uses no future QSO points');
assert.equal(values.at(-1).multiplier, history.finalState.points, 'product marginal converges to accumulated QSO points');
const cutoffValues = multiplierValueProgress(source, valueTarget, selection.start, source.dated[0].ts);
assert.equal(cutoffValues.at(-1).multiplier, history.rows[0].points, 'cutoff includes ties but excludes subsequent QSOs');
assert.equal(hourlyScores.supported, true, hourlyScores.reason);
assert.equal(hourlyScores.rows.reduce((sum, row) => sum + row.stationScoreGrowth, 0), derived.scoring.computedScore);
assert.equal(historicalScoreBefore(history, history.rows[0].ts), product.score(emptyScoreState()), 'strict prefix excludes tied events at interval start');
assert.equal(historicalScoreBefore(history, history.rows[0].ts + 1), history.rows[0].score, 'equal timestamps enter the same state');
assert.equal(multiplierHourlyScoreGrowth(selectMultiplierOverview(source, { radio: source.radios[0] })).rows[0].stationScoreGrowth, hourlyScores.rows[0].stationScoreGrowth, 'displayed radio does not reset station score');
const efficiency = multiplierEfficiencyGrowth(selection, multiplierEfficiency(selection));
assert.equal(efficiency.rows.reduce((sum, row) => sum + row.scoreGrowth, 0) + efficiency.unassignedGrowth, derived.scoring.computedScore);
const radioSelection = selectMultiplierOverview(source, { radio: source.radios[0] });
const radioEfficiency = multiplierEfficiencyGrowth(radioSelection, multiplierEfficiency(radioSelection));
assert.equal(radioEfficiency.rows.reduce((sum, row) => sum + row.scoreGrowth, 0) + radioEfficiency.unassignedGrowth, derived.scoring.computedScore, 'filtered events remain in station reconciliation');
const waeEvents = [{ ts: 0, band: '20M', operatingStyleRole: 'RUN', txId: '0' }, { ts: 0, isQtc: true, band: '20M' }, { ts: 60000, band: '20M', operatingStyleRole: 'SEARCH', txId: '1' }];
const waeScoring = { multiplierModelSupported: true, computedScore: 14, computedPointsByIndex: [1, 5, 1], analyticalMetadata: { rule: spec.rule_sets.find((r) => r.id === 'wae'), contributions: [{ qsoCount: 1, band: '20M' }, { qtcCount: 5, band: '20M' }, { qsoCount: 1, band: '20M' }] }, multiplierCredits: [0, 2].map((qsoIndex) => ({ qsoIndex, group: 'country', rawCredit: 1, weightedCredit: 1, countingScope: 'per_band', scopeKey: '20M', entityKey: String(qsoIndex) })) };
const waeSource = buildMultiplierOverviewSource([waeEvents[0], waeEvents[2]], waeScoring, {}, waeEvents);
const waeSelection = selectMultiplierOverview(waeSource);
const waeEfficiency = multiplierEfficiencyGrowth(waeSelection, multiplierEfficiency(waeSelection));
assert.equal(waeEfficiency.supported, true);
assert.equal(waeEfficiency.unassignedGrowth, 5, 'QTC score growth is not attributed to a QSO style');
assert.equal(waeEfficiency.rows.reduce((sum, row) => sum + row.scoreGrowth, 0), 9);
const gapSelection = { start: 0, end: 3600000, timeline: [{ ts: 600000 }, { ts: 1200000 }], hourly: [{ start: 0, raw: 2 }] };
assert.deepEqual(multiplierPeriodHighlights(gapSelection).longestGap, { start: 1200000, end: 3600000, minutes: 40 });
assert.equal(multiplierPeriodHighlights({ ...gapSelection, timeline: [] }).longestGap.minutes, 60, 'no-credit interval includes the full selected span');
assert.equal(multiplierPeriodHighlights({ ...gapSelection, hourly: [] }).best, null);
for (const count of [1, 2, 4]) {
  const slots = ['A', 'B', 'C', 'D'].slice(0, count).map((id) => ({ id, label: `Log ${id}`, selection }));
  const html = renderMultiplierOverview(slots, { view: 'tradeoff' });
  assert.equal((html.match(/class="multiplier-overview-panel"/g) || []).length, count);
  assert.equal((html.match(/<h4>What-if scenarios<\/h4>/g) || []).length, count);
  assert.equal((html.match(/<fieldset>/g) || []).length, count * 3);
  assert.ok(html.includes('Insufficient evidence'));
  assert.ok(!html.includes('being implemented'));
}
const csv = multiplierOverviewCsv(selection, 'tradeoff');
assert.ok(csv.startsWith('Strategy,QSOs/hour assumption,'));
assert.ok(csv.includes('Multiplier hunt'));
assert.ok(csv.includes('Ordinary QSO points for marginal equivalence'));
const historyCsv = multiplierOverviewCsv(selection, 'value-history', { averagePoints: 7 });
assert.ok(historyCsv.startsWith('UTC,Opening balance,Multiplier alone score gain,'));
assert.ok(historyCsv.includes(',Yes,'), 'opening history sample is explicitly marked');
assert.ok(historyCsv.includes('Fixed eligible unworked target'));
assert.ok(historyCsv.includes('Ordinary QSO points assumption'));
assert.ok(historyCsv.includes('Rule ID'), 'historical export retains selection context');
const escaped = renderMultiplierOverview([{ id: 'A', label: '<script>bad</script>', selection }], { view: 'tradeoff', tradeoffBySlot: { A: { targetGroup: '"><img src=x onerror=bad>' } } });
assert.ok(!escaped.includes('<script>bad'));
assert.ok(!escaped.includes('<img src=x'));
const unsupported = renderMultiplierOverview([{ id: 'A', label: 'Log A', selection: selectMultiplierOverview(buildMultiplierOverviewSource([], {})) }]);
assert.ok(!unsupported.includes('0 raw credits'));
assert.ok(!unsupported.includes('Comparison unavailable'));
assert.ok(!unsupported.includes('multiplier-overview-csv'));
const sparseHourChart = overviewChart([{ label: 'Sparse hours', points: [
  { ts: 0, start: 0, end: 3600000, value: 1 },
  { ts: 7200000, start: 7200000, end: 10800000, value: 1 }
] }], 'Sparse');
const sparseHourBars = [...sparseHourChart.matchAll(/<rect class="multiplier-bar" data-start="(\d+)" data-end="(\d+)" x="([\d.]+)" y="([\d.]+)" width="([\d.]+)" height="([\d.]+)"/g)];
assert.equal(sparseHourBars.length, 2, 'both isolated activity hours remain visible as bars');
assert.deepEqual(sparseHourBars.map((bar) => bar.slice(1, 3).map(Number)), [[0, 3600000], [7200000, 10800000]], 'bars preserve each hourly interval');
assert.ok(sparseHourBars.every((bar) => Number(bar[5]) > 0 && Number(bar[6]) > 0), 'isolated bars have visible width and height');
assert.equal(Number(sparseHourBars[1][3]) - (Number(sparseHourBars[0][3]) + Number(sparseHourBars[0][5])), Number(sparseHourBars[0][5]), 'the empty hour remains a full-hour gap between bars');
const manyTimeline = { ...selection, timeline: Array.from({ length: 1000 }, (_, index) => ({ ...selection.timeline[0], index, qsoNumber: index + 1 })) };
const pagedHtml = renderMultiplierOverviewPanel(manyTimeline, { view: 'timeline', tablePages: { A: 1 } }, 'A');
assert.equal((pagedHtml.match(/class="multiplier-qso-link"/g) || []).length, 200);
assert.ok(pagedHtml.includes('data-qso-index="200"'));
assert.ok(!pagedHtml.includes('data-qso-index="0"'));
assert.equal(multiplierOverviewCsv(manyTimeline, 'timeline').split('\r\n').length, 1002, 'CSV includes the complete selection, not only the UI page');
const undatedQso = { ts: null, call: 'S50A', band: '20M', mode: 'CW', txId: '1' };
const undatedSelection = selectMultiplierOverview(buildMultiplierOverviewSource([undatedQso], { multiplierModelSupported: true, multiplierCredits: [{ qsoIndex: 0, group: 'country', scopeKey: '20M', entityKey: 'SLOVENIA', rawCredit: 1 }] }), { startTs: 0, endTs: 60000 });
const undatedHtml = renderMultiplierOverview([{ id: 'A', label: 'Log A', selection: undatedSelection }], { view: 'undated' });
assert.ok(undatedHtml.includes('1 raw credits'));
assert.ok(undatedHtml.includes('data-qso-index="0"'));
assert.ok(undatedHtml.includes('time-range membership cannot be established'));
const undatedCsv = multiplierOverviewCsv(undatedSelection, 'undated');
assert.ok(undatedCsv.includes('S50A'));
assert.ok(undatedCsv.includes('Unknown; not included in dated totals or rates'));
assert.ok(multiplierOverviewCsv(undatedSelection, 'hourly').includes('Outside recorded log evidence'));
console.log('Multiplier score adapters: PASS');
