import assert from 'node:assert/strict';
import { evaluateStrategy, strategyBreakEven, observedStrategyDefaults, buildTradeoff } from '../modules/multipliers/tradeoff-model.js';
import { normalizeMultiplierSettings } from '../modules/multipliers/settings.js';
import { emptyScoreState, multiplierMarginal } from '../modules/multipliers/score-adapter.js';

const product = { supported: true, score: (s) => s.points * s.raw };
const state = { ...emptyScoreState(), points: 10000, raw: 100, weighted: 100 };
const target = { group: 'country', band: '20M', countingScope: 'once_total', scopeKey: 'ALL', weight: 1 };
const assumptions = { rate: 0, averagePoints: 2, credits: 1, probability: 1, searchMinutes: 0 };
const result = evaluateStrategy(product, state, assumptions, 15, target);
assert.equal(result.expectedGain, 10202);
assert.equal(result.expectedQsos, 1, 'successful multiplier contacts count as QSOs');
assert.equal(result.ordinaryQsos, 0);
assert.deepEqual(multiplierMarginal(product, state, { ...target, averagePoints: 2 }), { multiplier: 10000, qso: 200, equivalentQsos: 50 });
assert.equal(evaluateStrategy(product, state, { ...assumptions, probability: 0.5 }, 15, target).expectedGain, 5101);

// The expected outcome of a nonlinear score differs from scoring expected inputs.
const nonlinear = { supported: true, score: (s) => s.points * s.raw * s.positiveQsoCount };
const nonlinearState = { ...state, positiveQsoCount: 10 };
const certain = evaluateStrategy(nonlinear, nonlinearState, assumptions, 15, target);
const uncertain = evaluateStrategy(nonlinear, nonlinearState, { ...assumptions, probability: 0.5 }, 15, target);
assert.equal(uncertain.expectedGain, certain.expectedGain / 2);
assert.notEqual(uncertain.expectedGain, (10001 * 100.5 * 10.5) - nonlinear.score(nonlinearState));
const fractional = evaluateStrategy(nonlinear, nonlinearState, { ...assumptions, credits: 0, rate: 2 }, 15, target);
const oneOrdinaryGain = 10002 * 100 * 11 - nonlinear.score(nonlinearState);
assert.equal(fractional.expectedGain, oneOrdinaryGain / 2, 'fractional QSO counts use adjacent discrete outcomes');

for (const change of [{ credits: 0.5 }, { probability: 1.1 }, { searchMinutes: 16 }, { rate: -1 }, { targetQsos: 0 }, { averagePoints: '' }]) {
  assert.equal(evaluateStrategy(product, state, { ...assumptions, ...change }, 15, target).supported, false, JSON.stringify(change));
}
assert.equal(evaluateStrategy({ supported: false, reason: 'Unknown formula' }, state, assumptions, 15, target).reason, 'Unknown formula');
const run = { ...assumptions, credits: 0, rate: 60 };
const baseline = evaluateStrategy(product, state, run, 15, target);
assert.equal(baseline.expectedGain, 3000);
const breakEven = strategyBreakEven(product, state, baseline.expectedGain, { ...assumptions, rate: 60, probability: 0 }, 15, target);
assert.ok(breakEven.minutes < 1e-6);
assert.equal(state.points, 10000, 'scenarios never mutate the historical state');
assert.equal(state.raw, 100);
const hour = 3600000;
const observedSource = { start: 0, dated: Array.from({ length: 20 }, (_, i) => ({ ts: (i + 1) * 60000, radio: '0', style: 'RUN', band: '20M', mode: 'CW', points: 2 })) };
observedSource.classifyHistoricalStyles = (qsos) => qsos.map(() => 'RUN');
const observed = observedStrategyDefaults(observedSource, hour, 60, { band: '20M', mode: 'CW' });
assert.equal(observed.run.rate, 20, 'elapsed UTC denominator includes idle minutes');
assert.equal(observed.run.elapsedMinutes, 60);
assert.equal(observed.run.observedMinutes, 20);
assert.equal(observedStrategyDefaults(observedSource, hour, 60, { band: '40M' }).run.sampleQsos, 0);
assert.equal(observedStrategyDefaults(observedSource, hour, 60, { mode: 'SSB' }).run.sampleQsos, 0);
assert.equal(observedStrategyDefaults(observedSource, hour, 60, { radio: '1' }).run.sampleQsos, 0);
observedSource.dated.push({ ts: hour + 1, radio: '0', style: 'RUN', band: '20M', mode: 'CW', points: 10000 });
assert.equal(observedStrategyDefaults(observedSource, hour, 60, { band: '20M' }).run.averagePoints, 2, 'future events do not change observed assumptions');
const uba = { supported: true, family: 'belgian-bonus', score: (s) => (s.points + (s.ubaValidCount ? Math.round(s.ubaBelgianPoints * s.ubaBelgianCount / s.ubaValidCount) : 0)) * s.raw };
const ubaState = { ...emptyScoreState(), points: 100, raw: 1, weighted: 1, ubaValidCount: 10, ubaBelgianCount: 10, ubaBelgianPoints: 100 };
const ubaScenario = { ...assumptions, rate: 4, averagePoints: 1, targetAveragePoints: 10, ordinaryBelgian: '0', targetBelgian: '1' };
const ubaResult = evaluateStrategy(uba, ubaState, ubaScenario, 15, target);
assert.equal(ubaResult.failureGain, -8, 'ordinary non-Belgian QSO dilutes the bonus');
assert.equal(ubaResult.successGain, 224, 'only the target adds Belgian counters and target-specific points');
assert.equal(evaluateStrategy(uba, ubaState, { ...ubaScenario, ordinaryBelgian: '' }, 15, target).supported, false);
const nonmonotonic = strategyBreakEven(uba, ubaState, 0, { ...ubaScenario, rate: 60, credits: 0, probability: 0 }, 15, target);
assert.equal(nonmonotonic.minutes, 15, 'a longer search interval can avoid UBA bonus dilution');
assert.ok(nonmonotonic.intervals.length > 0);
assert.match(nonmonotonic.reason, /nonmonotonic/);
assert.equal(evaluateStrategy({ ...product, family: 'band-product' }, state, assumptions, 15, { ...target, band: '' }).supported, false);
assert.match(buildTradeoff({}, { at: 1e300 }).reason, /timestamp is invalid/);
assert.match(buildTradeoff({}, { lookbackMinutes: -1 }).reason, /between 1 and 120/);
assert.match(buildTradeoff({}, { horizonMinutes: 500 }).reason, /Forecast horizon/);
assert.match(buildTradeoff({}, { averagePoints: -2 }).reason, /Ordinary QSO points/);
assert.deepEqual(normalizeMultiplierSettings({ tradeoffBySlot: { A: { at: 1e300, lookbackMinutes: 500 } } }), { tradeoffBySlot: { A: {} } });
const avhfc = { supported: true, family: 'band-product', rule: { id: 'avhfc_legacy' }, score: (s) => (s.bandPoints['20M'] || 0) * (s.bandMults['20M'] || 0) + s.distanceBonus };
const avState = { ...emptyScoreState(), points: 100, raw: 2, weighted: 2, bandPoints: { '20M': 100 }, bandMults: { '20M': 2 }, distanceBonus: 10 };
const scopedTarget = { ...target, countingScope: 'per_band', scopeKey: '20M' };
assert.equal(evaluateStrategy(avhfc, avState, assumptions, 15, scopedTarget).supported, false, 'distance bonus cannot silently default to zero');
const avResult = evaluateStrategy(avhfc, avState, { ...assumptions, rate: 4, ordinaryDistanceBonus: 5, targetDistanceBonus: 9 }, 15, scopedTarget);
assert.equal(avResult.failureGain, 9);
assert.equal(avResult.successGain, 126);
const sarl = { supported: true, family: 'additive', rule: { id: 'sarl_hf_2026' }, score: (s) => Math.round(s.points + 2 * s.raw + s.threeBandBonus) };
const sarlState = { ...emptyScoreState(), points: 100, raw: 10, weighted: 10 };
assert.equal(evaluateStrategy(sarl, sarlState, assumptions, 15, target).supported, false);
const sarlResult = evaluateStrategy(sarl, sarlState, { ...assumptions, rate: 4, probability: 0.5, ordinaryThirdBandProbability: 0.3, targetThirdBandProbability: 0.75 }, 15, target);
assert.ok(Math.abs(sarlResult.failureGain - 2.6) < 1e-10);
assert.ok(Math.abs(sarlResult.successGain - 8.1) < 1e-10);
assert.ok(Math.abs(sarlResult.expectedGain - 5.35) < 1e-10, 'expected third-band bonus is not rounded as if it were a deterministic score');
console.log('Multiplier tradeoff model: PASS');
